name: common
description: 飞宏IM共享公共组件库，包含通用工具、扩展、主题和国际化资源
version: 0.0.1
homepage: https://github.com/liony823/feihong_app_new
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # 网络请求
  dio: ^5.8.0+1

  # 工具库
  path: ^1.8.3
  intl: ^0.20.2
  device_info_plus: ^11.3.0
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.2
  uuid: ^4.3.1
  logger: ^2.5.0
  pinyin: ^3.3.0
  image_gallery_saver_plus: ^4.0.1
  jiffy: ^6.2.1
  
  # UI相关
  flutter_svg: ^2.0.7
  icons_plus: ^5.0.0
  flutter_spinkit: ^5.2.1
  flutter_form_builder: ^10.0.0
  oktoast: ^3.4.0
  toastification: ^3.0.1
  wechat_assets_picker: ^9.5.0
  wechat_camera_picker: ^4.3.7
  image_cropper: ^9.1.0
  extended_image: ^9.1.0
  azlistview: ^2.0.0
  easy_refresh: ^3.4.0
  skeletonizer: ^1.4.3
  flutter_advanced_avatar: ^1.5.2
  pretty_qr_code: ^3.3.0
  screenshot: ^3.0.0
  cached_network_image: ^3.4.1

  # 动画
  animate_do: ^3.3.4

  # webview
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.4
  webview_flutter_wkwebview: ^3.18.5
  
  
  # 国际化
  slang: ^4.4.1
  slang_flutter: ^4.4.0
  world_countries: ^2.0.2
  
  # JSON处理
  json_annotation: ^4.8.1
  freezed_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint:
  riverpod_lint:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.9.0
  freezed: ^3.0.3

dependency_overrides: 
  intl: ^0.20.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  

  assets:
    - assets/images/
    - assets/svgs/
    - assets/audio/
