import 'package:common/common.dart';
import 'package:skeletonizer/skeletonizer.dart';

class FakeUserHelper {
  static UserInfo get fakeUserInfo => UserInfo(
        uid: BoneMock.fullName,
        username: BoneMock.name,
        name: BoneMock.name,
        zone: BoneMock.country,
        phone: BoneMock.phone,
        introduction: BoneMock.longParagraph,
        mute: 0,
        top: 0,
        sex: 0,
        category: '1',
        shortNo: 'feihong_user',
        chatPwdOn: 0,
        screenshot: 0,
        revokeRemind: 0,
        receipt: 0,
        online: 0,
        lastOffline: 0,
        deviceFlag: 0,
        follow: 0,
        beDeleted: 0,
        beBlacklist: 0,
        isDestroy: 0,
        flame: 0,
        flameSecond: 0,
        code: '1',
        vercode: '1',
        sourceDesc: '1',
        remark: '1',
        isUploadAvatar: 0,
        status: 0,
        robot: 0,
        joinGroupInviteUid: '1',
        joinGroupInviteName: '1',
        groupMember: GroupMember(
          uid: BoneMock.fullName,
          name: BoneMock.name,
          groupNo: BoneMock.fullName,
          remark: BoneMock.fullName,
          role: 0,
          isDeleted: 0,
          status: 0,
          vercode: BoneMock.fullName,
          inviteUid: BoneMock.fullName,
          robot: 0,
          forbiddenExpirTime: 1713235200,
          createdAt: '1713235200',
          updatedAt: '1713235200',
        ),
      );
}
