name: common
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.0-70.0.dev
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # 响应式编程
  rxdart: ^0.28.0


  # 扩展
  ducafe_ui_core: ^1.0.1
  get_it: ^8.0.3
  json_annotation: ^4.8.1
  freezed_annotation: ^3.0.0
  flutter_form_builder: ^10.0.0
  form_builder_validators: ^11.1.2

  # 工具
  device_info_plus: ^11.3.0
  package_info_plus: ^8.3.0
  vibration: ^1.7.6
  shared_preferences: ^2.5.2
  stack_trace: ^1.12.1
  scroll_to_index: ^3.0.1

  # 网络请求
  dio: ^5.8.0+1

  # webview
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.4
  webview_flutter_wkwebview: ^3.18.5

  # 国际化
  intl: ^0.19.0
  slang: ^4.4.1
  slang_flutter: ^4.4.0
  world_countries: ^2.0.2
  country_flags: ^3.2.0

  # UI组件
  toastification: ^3.0.1
  cupertino_icons: ^1.0.8
  icons_plus: ^5.0.0
  flutter_svg: ^2.0.7
  loader_overlay: ^5.0.0
  persistent_bottom_nav_bar_v2: ^5.3.1
  azlistview: ^2.0.0
  extended_image: ^9.1.0
  glossy: ^0.0.5

  # IM SDK
  wukongimfluttersdk: 
    git:
      url: https://github.com/liony823/WuKongIMFlutterSDK.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.3
  slang_build_runner: ^4.4.2
  build_runner: ^2.4.6
  json_serializable: ^6.9.0

dependency_overrides:
  intl: ^0.20.2


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
