name: chat
description: 飞宏IM聊天模块，包含聊天界面、消息处理等功能
version: 0.0.1
homepage: https://github.com/liony823/WuKongIMFlutterSDK
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 状态管理
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # 路由
  auto_route: ^10.0.1
  
  # UI组件
  scroll_to_index: ^3.0.1
  flutter_slidable: ^4.0.0
  
  # IM SDK - 正常情况下应该在core中访问，这里是为了直接访问一些SDK特性
  wukongimfluttersdk: 
    git:
      url: https://github.com/liony823/WuKongIMFlutterSDK.git
      ref: master
  common:
    path: ../common

dev_dependencies:
  flutter_lints: ^5.0.0
  freezed: ^3.0.3
  build_runner: ^2.4.6
  auto_route_generator: ^10.0.1
  riverpod_generator: ^2.6.5
  json_serializable: ^6.9.0
  custom_lint:
  riverpod_lint: