name: contact
description: 飞宏IM通讯录模块，包含联系人列表、用户资料等功能
version: 0.0.1
homepage: https://github.com/liony823/feihong_app_new
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
    
  # 状态管理
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  
  # 路由
  auto_route: ^10.0.1
  
  # UI组件
  azlistview: ^2.0.0
  icons_plus: ^5.0.0
  skeletonizer: ^2.0.1


    # 注解
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.6.1

  common:
    path: ../common

  core:
    path: ../core

  stream_ui:
    path: ../stream_ui


dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  freezed: ^3.0.3
  auto_route_generator: ^10.0.1
  riverpod_generator: ^2.6.5
  json_serializable: ^6.9.0
  custom_lint:
  riverpod_lint:



dependency_overrides: 
  intl: ^0.20.2

